### ISSUE TITLE
After adding substitutions, most of them disappeared

### ISSUE THREAD

**Issue by JaiBri** [BambusControl/obsidian-substitutions#1]
Basically what the title says. I have freshly downloaded it, added around 10 substitutions, restarted Obsidian and most of them (expect 2) were gone

**Comment by BambusControl** [comment]
Fixed in [Release 0.2.0](https://github.com/BambusControl/obsidian-substitutions/releases/tag/0.2.0)

Thanks for the heads up!
Overlooked the saving of more than one new substitutions, so it didn't work consistently.
